config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "products#index"

  resources :products do
    resources :reviews
  end

  resource :cart, only: [:show]

  resources :order_items

  resources :accounts

  resources :orders

  resources :charges

end

app/models/account.rb
class Account < ApplicationRecord
  has_one :user
  has_many :orders
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_items
  belongs_to :account
  before_save :update_total
  before_create :update_status


  def calculate_total
    self.order_items.collect { |item| item.product.price * item.quantity }.sum
  end

  private

  def update_status
    if self.status == nil?
      self.status == "In progress"
    end
  end

    def update_total
      self.total_price = calculate_total
    end
  end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :product

  # validates :quantity, :presence => true
end

app/models/product.rb
class Product < ApplicationRecord
validates :name, :description, presence: true
validates :price, numericality: true, presence: true
has_many :reviews
has_many :order_items

  has_attached_file :image
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/



end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :product

  validates :author, :content, :presence => true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

#callback method to create an account
 after_create :save_account

  def save_account
    Account.create(user_id: self.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_order, :current_order_quantity, :reset_session

  def current_order
    if session[:order_id]
      Order.find(session[:order_id])
    else
      Order.new
    end
  end

  def current_order_quantity
    quantity = 0
    current_order.order_items.each do |item|
      quantity += item.quantity
    end
    return quantity
  end

  def reset_session
  @_request.reset_session
end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  def show
    @order_items = current_order.order_items
    respond_to do |format|
      format.html { redirect_to products_url }
      format.js
    end
  end
end

app/controllers/charges_controller.rb
include ActionView::Helpers::NumberHelper
class ChargesController < ApplicationController

  def new
    @amount = number_to_currency(current_order.calculate_total)
  end

  def create
    # Amount in cents
    @formatted_sum = current_order.calculate_total.to_i

    customer = Stripe::Customer.create(
    :email => params[:stripeEmail],
    :source  => params[:stripeToken]
    )

    charge = Stripe::Charge.create(
    :customer    => customer.id,
    :amount      => @formatted_sum,
    :description => 'Rails Stripe customer',
    :currency    => 'usd'
    )

  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_charge_path
  end

end

app/controllers/order_items_controller.rb
class OrderItemsController < ApplicationController

  def create
    @account = Account.where(user_id: current_user.id).first
    @order = current_order
    @item = @order.order_items.new(item_params)
    @order.account_id = @account.id
    @order.save
    session[:order_id] = @order.id
    redirect_to products_path
  end

  def destroy
    @order = current_order
    @item = @order.order_items.find(params[:id])
    @item.destroy
    @order.save
    redirect_to cart_path
  end

  private

  def item_params
    params.require(:order_item).permit(:quantity, :product_id, :order_id)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
    @order_item = current_order.order_items.new
  end

  def show
    @product = Product.find(params[:id])

  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.find(params[:id])
    if @product.save
    flash[:notice] = "Product successfully added!"
      redirect_to  products_path
    else
      render :new
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      flash[:notice] = "Product successfully updated!"
        redirect_to product_path(@product)
      else
        flash[:notice]="Product update failed"
        render :edit
      end
  end

  def destroy
    @product = Product.find(params[:id])
    if @product.destroy
      flash[:notice]="Product successfully added!"
      redirect_to products_path
    end
  end

private
  def product_params
    # Use strict parameters, replace placeholder info below with your class' actual attributes
    params.require(:product).permit(:name, :description, :price, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def is_admin?
    current_user && current_user.admin
  end

end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/views/carts/show.erb
<% if @order_items.any? %>
  <% @order_items.each do |item| %>
    <p><%= item.product.name %> | <%= link_to "Delete", order_item_path(item), :data => {:confirm => "You sure?", :method => "delete"} %></p>
    <p> Unit Price: <%= number_to_currency item.product.price %> | Quantity: <%= item.quantity %> | Total Price: <%= number_to_currency (item.product.price * item.quantity) %></p>
  <% end %>
  <p>Your Total: <%= number_to_currency current_order.total_price %></p>
    <%= link_to 'Checkout', new_charge_path, class: 'btn btn-success' %>
<% else %>
  <p>Your shopping cart is empty.</p>
<% end %>

app/views/charges/create.html.erb
<h2>Thanks, you paid <%= @amount %>!</h2>

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
    <label class="amount">
      <span>Amount:<%= @amount %></span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="A month's subscription"
          data-amount="<%= @amount * 100 %>"
          data-locale="auto">
    </script>
<% end %>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EStore</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://js.stripe.com/v3/"></script>

  </head>

  <body>
    <div class="nav">
        <ul>
          <div class="nav-left">
            <li class="home"><%= link_to "Home", root_path %></li>
            <% if current_user %>
              <li class="products"><%= link_to "Products", products_path %></li>
            <% end %>
            <% if current_user %>
              <li class="products"><%= link_to "My Cart", cart_path %>
                <% if current_order %>
                  (<%= current_order_quantity %>)
                <% else %>
                  (0)
                <% end %>
              </li>
            <% end %>
          </div>
          <div class="nav-right">
          <% if current_user %>
              <li class="user">
                <span class="email_label"><%= current_user.email %></span>
                <% if is_admin? %>
                  <span class="admin_label">(ADMIN)</span>
                <% end  %>
              </li>
              <li>  <%= link_to "Sign out", destroy_user_session_path, method: 'delete' %> </li>
          <% else %>
              <li><%= link_to "Sign in", new_user_session_path %> | <%= link_to "Sign up", new_user_registration_path %></li>
          <% end %>
          </div>
        </ul>
      </div>

    <div class="jumbotron">

    </div>


    <div class="container">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </div>

  </body>
</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/products/_form.html.erb
<%= render "layouts/errors", :object => @product %>

<%= form_for @product do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <br>
  <%= f.label :description %>
  <%= f.text_area :description %>
  <br>
  <%= f.label :price %>
  <%= f.text_field :price %>
  <br>
  <%= f.label :image %>
  <%= f.file_field :image %>
  <br>
  <%= f.submit "Submit" %>
<% end %>

app/views/products/_show.html.erb
<div class="row clearfix">
  <div class="card">
    <div class="card-block">
      <h3><%= @product.name %></h3>
      <h4> <%= @product.description %></h4>
      <%= image_tag @product.image %>
    </div>
  </div>
</div>
<br>
<% if is_admin? %>
<div class="panel panel-info">
  <div class="panel-body">
    <p><%= link_to "Edit", edit_product_path(@product) %></p>
    <p><%= link_to "Delete", product_path(@product),
                             :data => {:confirm => "You sure?",
                                       :method => "delete"} %></p>
    <p><%= link_to "Return to products", products_path %></p>
  </div>
</div>
<% end %>

app/views/products/edit.html.erb
<h1>Edit Product</h1>

<%= render "form" %>

app/views/products/index.html.erb
<% if is_admin? %>
<div class="panel panel-info">
  <div class="panel-body">
    <p>Hello Admin! </p>
    <%= link_to "Add New Product", new_product_path %>
  </div>
</div>
<% end %>

<div class="clearfix row">
  <div class="col-md-6">
    <h3>Products</h3>

    <% @products.each do |product| %>
     <p><%= link_to product.name, product_path(product),remote: true %> | <%= number_to_currency(product.price, raise: true) %>
     <%= form_for @order_item, remote: true do |f| %>
       <%= f.hidden_field :product_id, value: product.id %>
       <%= f.number_field :quantity %>
       <%= f.submit "Add to cart" %>
     <% end %></p>
    <% end %>
  </div>


<div class="col-md-6">
  <div id="product-info">
    <!-- #partial -->
  </div>
</div>

</div>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render "form" %>

app/views/products/show.html.erb
<div class="row clearfix">
  <div class="card">
    <div class="card-block">
      <h2>Product info:</h2>
      <h3><%= @product.name %></h3>
      <h4> <%= @product.description %></h4>
      <%= image_tag @product.image %>
    </div>
  </div>
</div>
<br>
<% if is_admin? %>
<div class="panel panel-info">
  <div class="panel-body">
    <p><%= link_to "Edit", edit_product_path(@product) %></p>
    <p><%= link_to "Delete", product_path(@product),
                             :data => {:confirm => "You sure?",
                                       :method => "delete"} %></p>
    <p><%= link_to "Return to products", products_path %></p>
  </div>
</div>
<% end %>

app/views/products/show.js.erb
$('#product-info').html("<%= j render(partial: 'show') %>");